name: flutter_paginatrix
description: A simple, backend-agnostic pagination engine with UI widgets for Flutter
version: 1.0.1
homepage: https://github.com/MhamadHwidi7/flutter_paginatrix
repository: https://github.com/MhamadHwidi7/flutter_paginatrix
issue_tracker: https://github.com/MhamadHwidi7/flutter_paginatrix/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Immutability & unions
  freezed_annotation: ^3.1.0
  equatable: ^2.0.7
  
  # HTTP client
  dio: ^5.4.0
  
  # JSON serialization
  json_annotation: ^4.9.0
  
  # State management
  flutter_bloc: ^9.1.1
  
  # Skeleton loading effect
  skeletonizer: ^2.1.0
  
  # Toast notifications
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  # injectable_generator removed
  
  # Testing
  mockito: ^5.4.4
  test: ^1.24.9
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Documentation
  dartdoc: ^8.3.4

flutter:
  uses-material-design: true

# Enable code generation
# Note: dependency_overrides removed - not needed for publishing
# If you need it for local development, add it back
# dependency_overrides:
#   meta: ^1.11.0