name: search_advanced
description: Advanced search, filter, and sort example for flutter_paginatrix
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_paginatrix:
    path: ../../../
  shared:
    path: ../shared
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.4.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

