name: example_list
description: List view example for flutter_paginatrix
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_paginatrix:
    path: ../../
  flutter_bloc: ^8.1.6
  dio: ^5.4.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.10.1

flutter:
  uses-material-design: true

